import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsOptional, IsString, MaxLength } from 'class-validator';

export class CreateStoryTagDto {
  @ApiProperty({
    description: 'The display name of the story tag',
    example: 'Monsters',
  })
  @IsString()
  @IsNotEmpty()
  @MaxLength(100)
  name: string;

  @ApiProperty({
    description: 'Slug version of the tag (autogenerated if omitted)',
    example: 'monsters',
    required: false,
  })
  @IsString()
  @IsOptional()
  @MaxLength(120)
  slug?: string;
}