export const GUEST_SESSION_CREATED = 'GUEST_SESSION_CREATED';
export const GUEST_STORY_ACCESSED = 'GUEST_STORY_ACCESSED';
export const GUEST_QUOTA_EXHAUSTED = 'GUEST_QUOTA_EXHAUSTED';

export const GUEST_ACTIVITY_ACTIONS = [
  GUEST_SESSION_CREATED,
  GUEST_STORY_ACCESSED,
  GUEST_QUOTA_EXHAUSTED,
] as const;
